name: Wait for deployment
description: |
  Block until a deployment is finished for the pushed commit,
  and get the URL for running any further tests.
branding:
  icon: clock
  color: black

inputs:
  github-token:
    description: Your GitHub access token
    required: true
  environment:
    description: The deployment environment to wait for
  timeout:
    description: The number of seconds after which to fail if no successful deployment is found.
    default: 300
  deployment-timeout:
    description: The number of seconds after which to fail if no deployment is found.
    default: 30
  interval:
    description: The number of seconds to wait between repeated checks for deployments.
    default: 5

outputs:
  url:
    description: The deployment URL
  id:
    description: The GitHub deployment id

runs:
  using: node12
  main: index.js

